// AI and machine learning — the shapes you need to know.

export const aiMlArticle = {
  id: "ai-ml",
  title: "AI and machine learning",
  keywords: [
    "ai", "ml", "neural network", "transformer", "llm", "embedding",
    "rag", "fine tune", "training", "inference", "token", "prompt",
    "diffusion", "gradient descent",
  ],
  summary:
    "AI/ML uses statistical models — especially neural networks — to learn patterns from data. Modern LLMs like Claude and GPT are transformers trained on huge text corpora. Knowing a few core concepts (tokens, embeddings, fine-tuning, RAG) is enough to build useful things without retraining a model.",
  sections: [
    { id: "ml-basics", title: "What machine learning is",
      keywords: ["ml", "machine learning", "data"],
      body: "Instead of writing explicit rules, feed a model examples and let it learn the pattern. Supervised = labelled pairs (email → spam/not). Unsupervised = find structure (cluster similar items). Reinforcement = learn from reward signals (games, robots). Modern 'AI' is mostly deep learning: neural networks with many layers." },
    { id: "neural-net", title: "Neural networks in one paragraph",
      keywords: ["neural network", "layer", "weight"],
      body: "Stacks of matrix multiplications with non-linearities. Each layer transforms its input into a new representation; the final layer produces an output. Training = adjust the weights (billions of them) via gradient descent so the output matches the target. 'Deep' just means many layers. Everything flashy (LLMs, image gen, self-driving) is a variant of this idea." },
    { id: "gradient-descent", title: "Gradient descent",
      keywords: ["gradient descent", "training", "optimization"],
      body: "The workhorse optimiser. Compute how each weight affects the loss (via backpropagation), then nudge each weight slightly in the direction that reduces loss. Repeat millions of times on millions of examples. Variants: SGD, Adam, AdamW. Requires a differentiable loss function and massive compute." },
    { id: "transformer", title: "The transformer",
      keywords: ["transformer", "attention", "architecture"],
      body: "Introduced in 2017 ('Attention Is All You Need'). Uses self-attention — each token attends to every other token — instead of recurrence. Parallelisable, so GPUs go brrr. Almost every modern LLM (GPT, Claude, Llama, Qwen, Gemini) is a transformer. Image models (ViT), speech models, and more use it too." },
    { id: "llm", title: "Large language models",
      keywords: ["llm", "gpt", "claude", "language model"],
      body: "Transformers trained on vast text corpora to predict the next token. Given 'The capital of France is', predict 'Paris' with high probability. At scale (billions of parameters, trillions of tokens) this simple objective produces models that reason, code, write, translate. Not magic — statistical pattern matching at enormous scale." },
    { id: "tokens", title: "Tokens",
      keywords: ["token", "bpe", "tokenizer"],
      body: "LLMs don't see characters or words directly — they see tokens. Byte-pair encoding splits text into sub-word units. 'Hello' might be one token; 'antidisestablishmentarianism' is several. 'Hello世界' is a bunch. Context windows and pricing are in tokens. Rough rule: 1 token ≈ 4 English chars ≈ 0.75 words." },
    { id: "context-window", title: "Context window",
      keywords: ["context", "window", "length"],
      body: "How much text the model can attend to in one go. GPT-4 had 8K then 32K then 128K. Claude has 200K-1M. Modern models handle entire books. Cost scales with context — more tokens in = more compute + latency. The window is also the model's memory; anything outside it is forgotten." },
    { id: "training-vs-inference", title: "Training vs inference",
      keywords: ["training", "inference", "cost"],
      body: "Training = making the model. Requires thousands of GPUs for months, costs millions to tens of millions. Done once per model. Inference = using the model. Much cheaper per call, but scales with usage. For an app, you almost never train — you use existing models. Fine-tuning sits between, cheaper than training from scratch." },
    { id: "prompt-engineering", title: "Prompt engineering",
      keywords: ["prompt", "system", "instruction"],
      body: "LLM output depends heavily on how you ask. Be specific about role, format, constraints, examples. System prompt sets behaviour; user messages ask. Chain-of-thought ('think step by step') improves reasoning. Few-shot (showing examples) teaches format. Prompt engineering is mostly clear writing." },
    { id: "few-shot", title: "Zero-shot, few-shot, in-context learning",
      keywords: ["few shot", "zero shot", "in context"],
      body: "Zero-shot = ask without examples. Few-shot = include 2-10 input/output examples in the prompt, model follows the pattern. In-context learning = the model learns from what's in its context window without updating weights. Cheap, fast, easy to change. Often enough to avoid fine-tuning." },
    { id: "fine-tune", title: "Fine-tuning",
      keywords: ["fine tune", "customize", "adapt"],
      body: "Take a pre-trained model and continue training on your specific data. Updates weights to specialise. Good for: consistent format, domain jargon, tone-of-voice. Bad for: teaching new facts (use RAG instead). LoRA is a cheaper variant — train small 'adapter' matrices instead of full weights. Modern tooling (OpenAI, Anthropic, HuggingFace, Together AI) makes it 1-click-ish." },
    { id: "embedding", title: "Embeddings",
      keywords: ["embedding", "vector", "semantic"],
      body: "A function that converts text (or image, or audio) into a fixed-length vector of numbers. Similar meanings map to similar vectors. 'king' - 'man' + 'woman' ≈ 'queen'. Used for semantic search, clustering, recommendation, RAG. Cheap (thousands per second), standard API from any provider." },
    { id: "vector-search", title: "Vector search",
      keywords: ["vector search", "similarity", "faiss"],
      body: "Given a query vector, find the most similar vectors in a database. Cosine similarity or dot product on embeddings. Libraries: FAISS (Meta), pgvector (Postgres), Pinecone, Weaviate, Chroma. The core of modern 'semantic search' and the retrieval half of RAG." },
    { id: "rag", title: "Retrieval-augmented generation (RAG)",
      keywords: ["rag", "retrieval", "augmented"],
      body: "Combine a retriever (vector search over your docs) with a generator (LLM). Query → retrieve top-k relevant chunks → stuff them into the prompt → LLM answers grounded in your data. No fine-tuning needed. Used for company-specific chatbots, doc Q&A, search. Viontra's AI Pro role uses this pattern." },
    { id: "hallucination", title: "Hallucination",
      keywords: ["hallucination", "confabulate", "wrong"],
      body: "LLMs produce fluent, confident-sounding text that's factually wrong. They don't 'know' — they predict plausible continuations. Mitigations: RAG (grounds answers in real docs), citations (link to sources), lower temperature (less creative), self-consistency (multiple samples), and accepting that a model saying something doesn't make it true." },
    { id: "evals", title: "Evaluations",
      keywords: ["eval", "test", "benchmark"],
      body: "How do you know your LLM-based feature is good? Build evals: a fixed set of inputs with expected outputs or rubrics, grade each response. Run evals on every prompt/model change. 'Vibes' and demo-driven development fail at scale. Eval-driven development is the LLM equivalent of unit testing." },
    { id: "temperature", title: "Temperature and sampling",
      keywords: ["temperature", "sampling", "top-p"],
      body: "Temperature = randomness. 0 = deterministic (same input always gives same output), 1 = normal, 2+ = wild. Lower for factual/code tasks; higher for creative. top-p (nucleus sampling) truncates the tail — only consider tokens whose cumulative probability is under p. top-k truncates to the k most likely tokens." },
    { id: "safety", title: "Safety and guardrails",
      keywords: ["safety", "alignment", "guardrail"],
      body: "Models can be tricked into producing harmful content, leaking training data, or following injected instructions. Guardrails: system prompts that specify what NOT to do, content filters, rate limits, human review for high-risk outputs, don't trust user input to dictate actions. Claude and GPT have RLHF (Reinforcement Learning from Human Feedback) baked in; you still layer app-level controls." },
    { id: "diffusion", title: "Diffusion models",
      keywords: ["diffusion", "image", "stable diffusion"],
      body: "How image models (DALL-E, Stable Diffusion, Midjourney) work. Start with noise, iteratively 'denoise' toward an image that matches a text prompt. Controllable via prompts, LoRA, ControlNet. Video, audio, and 3D diffusion are growing fast. Completely different architecture from transformers but shares the 'train on massive data, use for generation' pattern." },
    { id: "open-vs-closed", title: "Open vs closed models",
      keywords: ["open source", "closed", "llama", "claude"],
      body: "Closed: Claude (Anthropic), GPT (OpenAI), Gemini (Google). Best quality, pay per token, closed weights. Open: Llama (Meta), Qwen (Alibaba), Mistral, Phi (MS). Weights publicly released, run yourself, customise, free. Gap has narrowed — open models are great for many tasks. Viontra uses open models (Qwen) via WebLLM precisely for this — no API key, self-hosted." },
  ],
};
