// Algorithms & data structures — the core CS toolkit.

export const algorithmsArticle = {
  id: "algorithms",
  title: "Algorithms and data structures",
  keywords: [
    "algorithm", "data structure", "big o", "complexity", "array",
    "linked list", "hash table", "tree", "graph", "sort", "search",
    "recursion", "dynamic programming", "binary search",
  ],
  summary:
    "Algorithms and data structures are the core vocabulary of computer science. Pick the right structure for the access pattern, pick the right algorithm for the size — the difference between O(n) and O(n²) is the difference between 1 second and a week.",
  sections: [
    { id: "big-o", title: "Big O notation",
      keywords: ["big o", "complexity", "time", "space"],
      body: "Big O describes how an algorithm's cost grows with input size. O(1) = constant, O(log n) = logarithmic, O(n) = linear, O(n log n) = linearithmic (sorting), O(n²) = quadratic (nested loops over n), O(2ⁿ) = exponential (avoid). Always look at worst case. A fast algorithm on small inputs can dominate a slow one despite worse constants." },
    { id: "arrays", title: "Arrays",
      keywords: ["array", "list", "vector"],
      body: "Contiguous memory, fixed or dynamic size. Access by index is O(1). Append amortised O(1) for dynamic arrays. Insert/delete in the middle is O(n) because everything after shifts. Ideal when you read a lot by index and rarely insert in the middle." },
    { id: "linked-list", title: "Linked lists",
      keywords: ["linked list", "node", "pointer"],
      body: "Nodes scattered through memory, each holding a value and a pointer to the next. Insert/delete at a known node is O(1). Access by index is O(n). Rarely the right answer in practice — CPU caches hate them. Useful for queues, deques, and adjacency lists." },
    { id: "hash-table", title: "Hash tables / maps",
      keywords: ["hash", "map", "dictionary", "object"],
      body: "Keys → values via a hash function, average O(1) lookup and insert. Collisions resolved by chaining (buckets) or open addressing (probing). Worst case O(n) if the hash is terrible or an attacker crafts inputs. JavaScript's plain objects and Map both use hash tables under the hood." },
    { id: "set", title: "Sets",
      keywords: ["set", "unique", "membership"],
      body: "Hash tables without values — membership check in O(1). Use Set instead of `array.includes()` whenever you're checking 'is X in this collection?' more than a handful of times. Sets are also how you deduplicate: `[...new Set(arr)]`." },
    { id: "stack-queue", title: "Stacks and queues",
      keywords: ["stack", "queue", "lifo", "fifo"],
      body: "Stack: last in, first out (push/pop). Think call stack, undo history, browser back. Queue: first in, first out (enqueue/dequeue). Think task schedulers, event loops, print jobs. Both are O(1) at their working end; implement with an array or linked list." },
    { id: "tree", title: "Trees",
      keywords: ["tree", "binary tree", "parent", "child"],
      body: "Hierarchical nodes with one parent and zero or more children. Binary trees have at most 2 children per node. Balanced binary search trees (AVL, red-black) give O(log n) insert/find/delete. The DOM, file systems, and parsed syntax are all trees. Traversals: pre-order, in-order, post-order, level-order." },
    { id: "heap", title: "Heaps / priority queues",
      keywords: ["heap", "priority queue", "min heap"],
      body: "A binary heap is an array-backed tree where each parent is smaller (min-heap) or larger (max-heap) than its children. Insert and extract-min are O(log n). Used for priority queues, job schedulers, Dijkstra's algorithm, and 'top-k' problems." },
    { id: "graph", title: "Graphs",
      keywords: ["graph", "vertex", "edge", "node"],
      body: "Vertices connected by edges. Directed vs undirected, weighted vs unweighted. Represented as adjacency lists (an array of neighbour arrays) or adjacency matrices. Model anything relational: social networks, road maps, web links, dependency graphs, state machines." },
    { id: "bfs-dfs", title: "BFS and DFS",
      keywords: ["bfs", "dfs", "traversal", "search"],
      body: "Breadth-first search uses a queue, explores nearest nodes first, finds shortest paths in unweighted graphs. Depth-first search uses a stack (or recursion), explores one branch fully before backtracking, good for detecting cycles, topological sort, connected components. Both O(V + E)." },
    { id: "binary-search", title: "Binary search",
      keywords: ["binary search", "sorted", "log n"],
      body: "On a SORTED array, jump to the middle, decide if the target is in the left or right half, repeat. O(log n). Every time you hear 'find efficiently in a sorted collection,' the answer is binary search. Tricky to get right — off-by-one errors and infinite loops are common bugs." },
    { id: "sorting", title: "Sorting",
      keywords: ["sort", "merge sort", "quicksort", "timsort"],
      body: "Comparison-based sorts bottom out at O(n log n). Quicksort (average O(n log n), worst O(n²), in-place), Mergesort (stable, O(n log n) always, extra space), Timsort (the hybrid used by Python and JS `.sort()`). Non-comparison sorts like radix/counting hit O(n) for integer keys. Don't write your own — use the language's built-in unless you have a specific reason." },
    { id: "recursion", title: "Recursion",
      keywords: ["recursion", "base case", "recursive"],
      body: "A function that calls itself on a smaller problem until reaching a base case. Natural fit for tree traversal, divide-and-conquer, backtracking. Watch out for stack overflow on deep recursion — iterative solutions or tail-call optimisation help. Every recursion can be rewritten iteratively with an explicit stack." },
    { id: "memoization", title: "Memoisation and caching",
      keywords: ["memoization", "cache", "dp"],
      body: "Cache results of expensive pure functions keyed by inputs. Turns recomputation into a lookup. Fibonacci naively is O(2ⁿ); with memoisation it's O(n). Be mindful of cache size and eviction (LRU is the usual choice). Memoisation only works on pure functions — side effects break the cache contract." },
    { id: "dp", title: "Dynamic programming",
      keywords: ["dynamic programming", "dp", "subproblem", "memoize"],
      body: "Break a problem into overlapping subproblems, solve each once, combine. Two styles: top-down (recursion + memoisation) or bottom-up (fill a table). Classic problems: longest common subsequence, edit distance, knapsack, shortest paths. Recognise DP when a brute-force recursion has overlapping subtrees." },
    { id: "greedy", title: "Greedy algorithms",
      keywords: ["greedy", "local optimum"],
      body: "Make the locally best choice at each step and hope it leads to a global optimum. Works when the problem has the greedy-choice property (e.g., interval scheduling, Huffman coding, Dijkstra's). Often gives good approximations when it doesn't give the exact answer. Simpler than DP when it applies." },
    { id: "two-pointer", title: "Two-pointer and sliding window",
      keywords: ["two pointer", "sliding window"],
      body: "Two pointers moving through an array — one at each end, or one fast one slow, or both from the left. Solves many 'find a pair/subarray that sums to X' problems in O(n) instead of O(n²). Sliding window expands/contracts a range as you scan — classic for 'longest substring without repeats' style problems." },
    { id: "hash-trick", title: "The hash-map trick",
      keywords: ["hash map", "lookup", "trick", "count"],
      body: "Most 'find X efficiently' interview problems reduce to: scan once, build a hash map, scan again (or inline both). Two-sum, group anagrams, subarray-sum-equals-k — all hash-map solutions. When you see O(n²) brute force and the problem involves lookups or counts, reach for a hash map." },
    { id: "bit-ops", title: "Bit manipulation",
      keywords: ["bit", "bitwise", "xor", "mask"],
      body: "AND (&), OR (|), XOR (^), NOT (~), left shift (<<), right shift (>>). XOR tricks: `a ^ b ^ b === a`, finds single non-duplicated element. Bit masks pack flags into a single integer. Check even/odd with `x & 1`. Rarely necessary in high-level code but crucial in low-level, graphics, cryptography, compression." },
    { id: "pick-structure", title: "How to pick a data structure",
      keywords: ["pick", "choose", "choice"],
      body: "Ask: (1) What operations do I do most? Lookup, insert, delete, iterate in order? (2) How big is n? (3) Do I need ordering or stability? Lookup by key → hash map. Ordered set/map → tree. Always-latest-or-oldest → stack/queue. Top-k or priority-based → heap. Relationships → graph. Don't invent; pick from the standard toolbox first." },
    { id: "complexity-in-practice", title: "Complexity in practice",
      keywords: ["practical", "constant factor", "cache"],
      body: "Big O hides constants and cache effects. A linear scan of a flat array beats a logarithmic tree traversal on small n because of cache locality. Memory allocation is slow. Profile before optimising. The right algorithm is the one that's fast enough AND easy to understand — not the cleverest one on paper." },
  ],
};
