// Business fundamentals — how to make something people want and get paid for it.

export const business101Article = {
  id: "business-101",
  title: "Business fundamentals",
  keywords: [
    "business", "startup", "mvp", "product market fit", "pricing",
    "revenue", "customer", "unit economics", "ltv", "cac",
    "founder", "pitch", "investor",
  ],
  summary:
    "Building a business is separate from building a product. Product is 'does this work?' Business is 'can this sell, reliably, at a profit, at scale?' Most startups die not because the product broke but because the business around it never formed.",
  sections: [
    { id: "pmf", title: "Product–market fit",
      keywords: ["pmf", "product market fit", "sean ellis"],
      body: "PMF = you've found a market that wants your product so badly that you're pulled by demand rather than pushing. Sean Ellis test: 40%+ of users would be 'very disappointed' if your product disappeared. Before PMF, your only job is finding it. After PMF, your job is scaling. Most founders fool themselves that they have PMF before they do." },
    { id: "problem-first", title: "Start with a problem, not a solution",
      keywords: ["problem", "pain", "market"],
      body: "A great product solves a real, painful, frequent problem for a specific audience. Interview people. Ask about their workflow, not your idea. Listen for the words 'I hate when...', 'I waste time on...', 'there's nothing good for...'. If the problem isn't painful, people won't pay. If it isn't frequent, they won't stick around." },
    { id: "niche", title: "Start niche, then expand",
      keywords: ["niche", "audience", "focus"],
      body: "'A small set of users who love you' beats 'a huge set of users who kinda like you.' Pick a narrow, underserved audience and nail their problem completely. Facebook started at Harvard. Stripe started with YC startups. Once you dominate a niche you can expand laterally. Trying to be for everyone means being for no one." },
    { id: "mvp", title: "The real MVP",
      keywords: ["mvp", "minimum viable", "test"],
      body: "MVP = the smallest thing that tests the riskiest assumption. It's not v0.1 of the final product — it's an experiment. Sometimes a landing page with a signup form. Sometimes a concierge service run by hand. Sometimes a Figma click-through. Build only what's needed to learn; scale is a later problem." },
    { id: "sell-before-build", title: "Sell before you build",
      keywords: ["presell", "validate", "paying"],
      body: "The only reliable signal of real demand is people paying. Before building, try to sell it. Pitch deck to 10 target buyers. Pre-orders, letter of intent, paid pilot. If you can't sell a vision, the product won't save you. If you can sell a vision, the product mostly has to not be terrible." },
    { id: "pricing", title: "Pricing",
      keywords: ["price", "pricing", "value"],
      body: "Price based on the value you deliver, not your cost. Most founders under-price — customers take it as a quality signal. Price tiers separate audiences: free/cheap for individuals, mid for teams, 'contact us' for enterprise. Never compete on price as a small player; you lose to the bigger player with deeper pockets." },
    { id: "business-model", title: "Business model",
      keywords: ["business model", "revenue", "subscription"],
      body: "How do you make money? Subscriptions (recurring), transactional (per use), marketplace (cut of transactions), ads (user attention as product), licensing, services, hardware. SaaS (subscriptions) dominates software because recurring revenue compounds. Pick one and be great at it; multi-model early = diluted focus." },
    { id: "ltv-cac", title: "LTV and CAC",
      keywords: ["ltv", "cac", "unit economics", "payback"],
      body: "LTV (lifetime value) = revenue per customer over their entire relationship. CAC (customer acquisition cost) = money spent to acquire one customer. LTV/CAC ratio of 3+ is healthy, below 1 means you're paying to lose customers. Payback period = how many months of revenue to recover CAC; under 12 months is strong." },
    { id: "churn", title: "Churn",
      keywords: ["churn", "retention", "cancel"],
      body: "Churn = % of customers leaving per period. 5% monthly churn means losing half your customers every year. Annual churn under 10% is great; under 5% is elite. Reducing churn by 1% often beats increasing acquisition by 10%. Talk to customers who cancel — their reasons are a roadmap." },
    { id: "distribution", title: "Distribution > product",
      keywords: ["distribution", "channel", "go to market"],
      body: "A great product with no distribution loses to an OK product with great distribution. Pick a channel (SEO, content, paid, partnerships, virality, direct sales, app store, community) and master it before diversifying. Each channel has its own physics — paid ads scale linearly with money, SEO compounds but takes years. Founders underestimate this." },
    { id: "marketing-honest", title: "Marketing — the honest version",
      keywords: ["marketing", "positioning"],
      body: "Marketing = helping the right people realise you exist and can solve their problem. Positioning: who is this for, what category is it in, what's it better at than alternatives. If you can't state those in one sentence, you'll waste money on ads that fail to convert. Write the positioning before you write code." },
    { id: "founder-market-fit", title: "Founder–market fit",
      keywords: ["founder", "experience", "unfair advantage"],
      body: "Why you? Do you have an unfair advantage — deep domain knowledge, unique access, a rare combination of skills? Building in a space you don't understand means learning on customers. The best founders either lived the problem for years or have spent hundreds of hours researching it. Outsiders CAN win but it's harder." },
    { id: "cofounder", title: "Cofounders",
      keywords: ["cofounder", "partner", "equity"],
      body: "Solo is possible but harder — you'll want a thought partner and complementary skills. Common split: technical + business. Don't split equity unevenly without reason. VEST equity over 4 years with a 1-year cliff (standard, non-negotiable for investors later). Discuss scenarios upfront: divorce, death, who leaves, who stays." },
    { id: "fundraising", title: "Fundraising — default alive",
      keywords: ["fundraising", "investor", "vc", "runway"],
      body: "Fundraising is NOT a milestone — it's a tool. 'Default alive' means your business pays its own bills; 'default dead' means you need to raise or die. Raise from a position of strength, for a specific growth phase, not to keep lights on. VC is equity-for-speed; not every company needs it. Bootstrapping is honourable and underrated." },
    { id: "pitching", title: "Pitching",
      keywords: ["pitch", "deck", "investor"],
      body: "Investor pitch structure: problem, solution, why now, market size, traction, business model, team, ask. Two minutes to hook, ten to close. Lead with traction if you have it. Show don't tell — demo > slides. Rehearse out loud 30+ times. Expect rejections; most pitches fail. One yes beats a hundred maybes." },
    { id: "hiring", title: "Hiring",
      keywords: ["hire", "team", "recruit"],
      body: "First hires set culture. Move slow, hire deliberately. Look for: smart, gets things done, fits the mission. Skills are trainable; values aren't. Reference checks from former managers (not the references the candidate gives) are gold. Don't hire to delegate fear; hire to multiply impact. Bad hires cost 3–5x their salary in lost time." },
    { id: "culture", title: "Culture = what you tolerate",
      keywords: ["culture", "values", "tolerate"],
      body: "Culture isn't posters or slogans. It's what behaviour gets rewarded and what doesn't. Tolerate mediocrity and the best people leave. Tolerate brilliance with bad behaviour and the healthy people leave. Founders set the tone in the first 10 hires. Write values when specific, testable behaviours are captured, not abstract virtues." },
    { id: "ruthless-prio", title: "Ruthless prioritisation",
      keywords: ["prioritize", "focus", "no"],
      body: "You will have 100 ideas and resources for 2 per quarter. The job is saying no. Ask: does this move the biggest number that matters? If not, cut. Most startups die of indigestion, not starvation — too many half-done things, not too few ideas." },
    { id: "speed", title: "Speed is a feature",
      keywords: ["speed", "velocity", "ship"],
      body: "Ship faster than you think is wise. Small decisions: decide in minutes. Big decisions: decide in a day. Reversible decisions: make them fast — you can undo. Irreversible: take time. Paul Graham: 'Launch early and iterate' (famous). The reality is the market teaches you things no plan does — get in the game." },
    { id: "metrics", title: "Measure what matters",
      keywords: ["metric", "kpi", "north star"],
      body: "Pick a North Star metric that reflects real user value (weekly active users, messages sent, revenue retained). Vanity metrics (pageviews, signups) feel good but don't predict success. Cohort analysis > snapshots. Dashboard everyone looks at daily. Decisions in the dark rely on opinions; with data, they rely on reality." },
    { id: "why-startups-fail", title: "Why startups fail",
      keywords: ["fail", "reason", "autopsy"],
      body: "CB Insights' classic autopsy: (1) no market need, (2) ran out of cash, (3) not the right team, (4) got outcompeted, (5) pricing/cost issues, (6) bad product, (7) lack of business model, (8) poor marketing. Notice #1 — most failures are building what no one wants. Find the want first; build second." },
  ],
};
