// Security fundamentals — the non-negotiables for shipping safe software.

export const securityArticle = {
  id: "security",
  title: "Security fundamentals",
  keywords: [
    "security", "owasp", "xss", "sql injection", "csrf", "auth",
    "oauth", "jwt", "password", "hash", "bcrypt", "tls", "secret",
    "encryption", "privacy",
  ],
  summary:
    "Software security is a continuous practice, not a feature. The biggest risks come from a small set of categories — injection, broken auth, sensitive data exposure, misconfigurations. Get the basics right and you've dodged 90% of the trouble.",
  sections: [
    { id: "threat-model", title: "Threat modelling",
      keywords: ["threat model", "risk", "attacker"],
      body: "Before building: ask who might attack, what they want, and how they'd try. Frameworks like STRIDE (Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege) help enumerate. Defence is prioritised by likelihood × impact. A thousand-dollar lock on a wooden door is wasted." },
    { id: "input-validation", title: "Never trust input",
      keywords: ["input", "validation", "boundary"],
      body: "Treat all input from outside your system (users, APIs, queue messages, environment) as hostile. Validate at the boundary where it enters: type, length, format, range, allowed values. Use schemas (Zod, Joi, Pydantic). Reject on failure; never silently coerce. Once data passes validation, internal code can trust it." },
    { id: "xss", title: "XSS — cross-site scripting",
      keywords: ["xss", "inject", "script", "escape"],
      body: "Attacker tricks your site into running their JavaScript in another user's browser. Three flavours: stored (your DB returns it), reflected (URL param echoed back), DOM-based (client JS writes untrusted data into HTML). Fix: always escape on output — use text nodes (`el.textContent`), not `innerHTML`. Frameworks (React, Vue) escape by default; don't dangerously opt out." },
    { id: "sql-injection", title: "SQL injection",
      keywords: ["sql injection", "query", "parameterized"],
      body: "Never build SQL by string-concatenating user input. Use parameterised queries (prepared statements): `db.query(\"SELECT * FROM users WHERE id = ?\", [id])`. The DB driver handles escaping and treats the input as data, never as code. ORMs do this automatically. If you're string-building SQL in 2026, stop and use the parameterised form." },
    { id: "csrf", title: "CSRF — cross-site request forgery",
      keywords: ["csrf", "xsrf", "samesite"],
      body: "Attacker hosts a form on evil.com that submits to bank.com; user's browser sends their bank cookies. Mitigations: (1) `SameSite=Lax|Strict` on auth cookies (modern default), (2) CSRF tokens — a random value in a cookie + form field that must match, (3) require custom headers (triggers CORS preflight). Pure token-in-Authorization-header APIs (no cookies) are not CSRF-vulnerable." },
    { id: "auth", title: "Authentication vs authorization",
      keywords: ["auth", "authn", "authz", "login"],
      body: "Authentication = who are you (login). Authorization = what are you allowed to do (permissions). Authenticate once, issue a token/session, then authorize on every request. Never re-derive permissions from the client — always check server-side. The phrase 'we check auth in the frontend' is the start of a breach." },
    { id: "passwords", title: "Passwords",
      keywords: ["password", "hash", "bcrypt", "argon2"],
      body: "Never store passwords — store a one-way hash with a strong algorithm: argon2id (preferred), bcrypt, scrypt. Never MD5/SHA1/SHA256 plain — those are fast and brute-force-able. Use the library's built-in salting. Enforce length, not complexity (a 16-char passphrase beats `P@ssw0rd!`). Support password managers. Offer 2FA." },
    { id: "2fa", title: "2FA / MFA",
      keywords: ["2fa", "mfa", "totp", "webauthn"],
      body: "Something you know (password) + something you have (phone, hardware key). TOTP (Google Authenticator) is fine — avoid SMS where possible (SIM-swap). WebAuthn/passkeys are the modern best answer: phishing-resistant, hardware-backed, no password needed. Offer recovery codes stored safely (print them, save in password manager)." },
    { id: "sessions", title: "Sessions vs tokens",
      keywords: ["session", "jwt", "token", "revoke"],
      body: "Sessions: a random ID in a cookie, state lives server-side. Easy to revoke (delete the session). JWTs: self-contained, verified by signature. Hard to revoke before expiry. Best practice: short-lived access tokens + long-lived refresh tokens, rotate on use, store in HttpOnly+Secure+SameSite cookies. Don't put JWTs in localStorage — XSS steals them." },
    { id: "oauth", title: "OAuth and OIDC",
      keywords: ["oauth", "oidc", "sso", "login"],
      body: "OAuth 2.0 = delegated authorization (let App A act on my behalf with Service B without sharing my password). OpenID Connect = identity layer on top of OAuth (authenticate the user). 'Sign in with Google' is OIDC. Use a library; don't roll your own. Always use Authorization Code + PKCE flow for SPAs and mobile." },
    { id: "secrets", title: "Secrets management",
      keywords: ["secret", "api key", "env", "vault"],
      body: "Never commit secrets to git. Use environment variables, or better, a secrets manager (AWS Secrets Manager, Vault, Doppler, 1Password). Rotate regularly. Different secrets per environment (dev/staging/prod). If you leak one, rotate immediately and audit usage. Pre-commit hooks (gitleaks) catch accidental pushes." },
    { id: "tls", title: "HTTPS everywhere",
      keywords: ["tls", "https", "certificate"],
      body: "Every production site: HTTPS only, HSTS header (tells browsers to never downgrade), modern TLS (1.2 minimum, 1.3 preferred), valid cert (Let's Encrypt is free and auto-renews). Redirect HTTP → HTTPS. Don't serve mixed content. Internal service-to-service also benefits from mTLS for authentication." },
    { id: "rate-limiting", title: "Rate limiting",
      keywords: ["rate limit", "throttle", "brute force"],
      body: "Limit requests per IP, per user, per endpoint. Stops brute-force password guessing, credential stuffing, scrapers, API abuse, accidental runaway clients. Token bucket and leaky bucket are the common algorithms. Return `429 Too Many Requests` with a `Retry-After` header. Login endpoints need especially tight limits." },
    { id: "logging-secrets", title: "Never log secrets",
      keywords: ["log", "secret", "pii"],
      body: "Don't log passwords, tokens, API keys, credit cards, SSNs. Redact them at the logger level if possible. PII (personally identifiable information) needs extra care under GDPR/CCPA. Centralised logs get reviewed by operators, shipped to SaaS vendors, retained for years — any secret in them is essentially leaked." },
    { id: "secure-defaults", title: "Secure defaults",
      keywords: ["default", "secure", "principle of least privilege"],
      body: "Default to deny, not allow. Default to private, not public. Principle of least privilege: give services/users the minimum permissions they need. S3 buckets default-private. DB user for the app has only the perms it needs (no DROP TABLE). Dev machines shouldn't have prod creds. Most breaches are misconfigurations." },
    { id: "deps", title: "Keep dependencies updated",
      keywords: ["dependency", "supply chain", "npm", "patch"],
      body: "Old libraries have known CVEs. Run `npm audit`, Dependabot, Snyk, or similar. Pin versions but update regularly. Be paranoid about typosquatted packages (`react-dom` vs `reactdom`). Supply-chain attacks are rising — review what you install, prefer popular maintained packages, avoid deps with one dependency for every small function." },
    { id: "csp", title: "Content Security Policy",
      keywords: ["csp", "content security policy", "header"],
      body: "CSP header tells the browser what scripts, styles, images, iframes are allowed. `script-src 'self'` blocks inline scripts and third-party JS — a huge XSS mitigation. Rolling out CSP takes effort (find all your inline scripts, move them). Start with report-only mode, review violations, then enforce." },
    { id: "owasp", title: "OWASP Top 10",
      keywords: ["owasp", "top 10", "vulnerability"],
      body: "Periodic list of the most common web vulnerabilities: (1) Broken access control, (2) Crypto failures, (3) Injection, (4) Insecure design, (5) Security misconfiguration, (6) Vulnerable/outdated components, (7) Identification/auth failures, (8) Software/data integrity failures, (9) Logging/monitoring failures, (10) SSRF. Read the list once a year." },
    { id: "incident", title: "Incident response",
      keywords: ["incident", "breach", "response", "postmortem"],
      body: "Have a runbook before you need it. Steps: detect, contain (disable leaked creds, patch, pull code), eradicate (remove attacker access), recover (restore service), learn (postmortem). Don't blame individuals — blame process. Communicate honestly with users about breaches that affect them (it's often legally required)." },
    { id: "mindset", title: "Security mindset",
      keywords: ["mindset", "defense in depth"],
      body: "Defense in depth: multiple layers, so a single failure doesn't breach. Assume breach: design so an attacker gaining one foothold can't pivot everywhere. Reduce attack surface: disable what you don't need (ports, services, admin endpoints). Paranoia is a feature. 'It probably won't happen' is not a threat model." },
  ],
};
