// System design — how to architect software that scales and stays sane.

export const systemDesignArticle = {
  id: "system-design",
  title: "System design",
  keywords: [
    "system design", "architecture", "scale", "microservice", "monolith",
    "cache", "queue", "load balancer", "database", "cap theorem",
    "sharding", "replication", "observability",
  ],
  summary:
    "System design is the art of arranging components — services, databases, caches, queues, load balancers — to meet requirements on throughput, latency, reliability, and cost. The right architecture is the simplest one that meets current needs with a clear path to scale when you actually need to.",
  sections: [
    { id: "monolith-first", title: "Monolith first",
      keywords: ["monolith", "simple", "start"],
      body: "Start with a single deployable application and a single database. It's easier to develop, deploy, debug, and refactor. The instinct to start with microservices usually costs you 6–12 months before you deliver any user-facing value. Split out services when a specific pain is real (team boundaries, independent scaling, different tech stacks) — not pre-emptively." },
    { id: "scale-axes", title: "Three axes of scaling",
      keywords: ["scale", "vertical", "horizontal", "sharding"],
      body: "(1) Vertical — bigger machines. Simple, fast, eventually hits a ceiling. (2) Horizontal — more machines running the same code, load-balanced. Almost always the answer for stateless services. (3) Functional — split responsibilities across different services. Only valuable once the system is big and teams need autonomy." },
    { id: "stateless", title: "Stateless services scale trivially",
      keywords: ["stateless", "scale", "session"],
      body: "If a request carries everything needed to serve it (user id in a JWT, query params, body), any replica can handle it. Adding replicas behind a load balancer is instant scaling. The moment you stash per-user state in memory, scaling breaks — push that state into a shared store (Redis, DB)." },
    { id: "database-first", title: "The database is usually the bottleneck",
      keywords: ["database", "bottleneck", "sql", "query"],
      body: "Almost every slow web service is slow at the DB. Measure: slow query logs, EXPLAIN plans, p99 latencies per query. Fix order: add missing indexes, rewrite the worst query, add a cache in front, then scale the DB. Bigger app servers rarely help." },
    { id: "indexing", title: "Indexing",
      keywords: ["index", "database", "btree"],
      body: "An index is a sorted auxiliary structure that lets the DB find rows without scanning the whole table. Add indexes for columns you filter, join, or sort on. Cost: disk space + slower writes. Look for missing indexes via query plans (`EXPLAIN`). Composite indexes matter — `(user_id, created_at)` is NOT the same as two separate indexes." },
    { id: "caching", title: "Caching",
      keywords: ["cache", "redis", "memcached", "ttl"],
      body: "Cache = store expensive results so you don't recompute. Layers: browser, CDN, reverse proxy, application memory, Redis/memcached, DB query cache. Rules: cache the smallest useful unit, set a TTL, invalidate on write, accept eventual inconsistency. 'There are only two hard things in CS: cache invalidation and naming things' — Phil Karlton, only half-joking." },
    { id: "queues", title: "Queues and async work",
      keywords: ["queue", "async", "worker", "sqs", "rabbitmq"],
      body: "Move slow or unreliable work off the request path. Web server writes a job to a queue (SQS, RabbitMQ, Redis, Postgres), workers pull and process. Benefits: smoother load, retries, backpressure, decoupling. Any task that takes more than ~100ms and isn't critical-path should be async: email sending, image processing, webhook fan-out, bulk operations." },
    { id: "load-balancer", title: "Load balancers",
      keywords: ["load balancer", "lb", "nginx", "alb"],
      body: "Sits in front of a pool of app servers, routes incoming requests. Algorithms: round-robin, least-connections, hash-based (sticky sessions). L4 (TCP) is fast and protocol-agnostic; L7 (HTTP) can route by path/header/cookie. Health checks drop dead backends. Terminate TLS here so your app servers don't do crypto." },
    { id: "cdn", title: "CDN for static + some dynamic",
      keywords: ["cdn", "edge", "static"],
      body: "Always put static assets (JS, CSS, images, fonts) behind a CDN. For dynamic responses, a CDN can still cache per-URL with short TTLs or 'stale-while-revalidate'. Edge functions (Cloudflare Workers, Vercel Edge) run your code close to the user — low-latency transformations without hitting origin." },
    { id: "sharding", title: "Sharding",
      keywords: ["sharding", "partition", "horizontal"],
      body: "Splitting one big DB into many smaller ones by some key (user_id, region). Each shard handles a subset of data. Enables horizontal scaling past one machine. Costs: hard to do cross-shard queries, hard to rebalance, hard to keep transactions atomic. Shard only when a single-node DB truly can't keep up." },
    { id: "replication", title: "Replication",
      keywords: ["replication", "replica", "read", "primary"],
      body: "Primary + read replicas: writes go to primary, reads go to replicas (eventual consistency lag). Great for read-heavy workloads. Also provides high availability — failover to a replica if primary dies. Multi-primary replication (write anywhere) is complex and conflict-prone; avoid unless you need it." },
    { id: "cap", title: "CAP theorem",
      keywords: ["cap", "consistency", "availability", "partition"],
      body: "During a network partition, a distributed system can have consistency OR availability, not both. Postgres/Spanner default to CP (refuse writes if partitioned). DynamoDB/Cassandra default to AP (accept writes, reconcile later). Reality is a spectrum — most systems tune for the common non-partitioned case." },
    { id: "consistency", title: "Consistency models",
      keywords: ["consistency", "eventual", "strong"],
      body: "Strong consistency: reads reflect all prior writes. Eventual: reads eventually reflect writes, with lag. Causal: related events observed in order. Read-your-writes: you see your own writes instantly, others may not. Pick the weakest model your app can tolerate — it's always faster and cheaper." },
    { id: "pub-sub", title: "Pub/sub and event-driven",
      keywords: ["pubsub", "event", "kafka", "streaming"],
      body: "Producers publish events to topics; subscribers consume. Kafka, Pulsar, Redis Streams, SNS+SQS. Decouples services — you can add new consumers without changing producers. Great for analytics pipelines, fan-out, audit logs. Exactly-once delivery is hard; build idempotent consumers so duplicates are harmless." },
    { id: "microservices", title: "Microservices — when to split",
      keywords: ["microservice", "split", "service"],
      body: "Split when: different parts need to scale independently, different teams need to ship without coordinating, different tech stacks are genuinely justified. DON'T split just because it's fashionable. A 10-person team running 50 services is a support nightmare. Conway's Law: your system reflects your org chart." },
    { id: "observability", title: "Observability — logs, metrics, traces",
      keywords: ["observability", "monitoring", "metrics", "tracing"],
      body: "Three pillars. Logs: timestamped text, structured (JSON). Metrics: numbers over time (Prometheus, StatsD) — rate, latency, error counts. Traces: follow a request through services (Jaeger, OpenTelemetry). In prod, you live in dashboards and log aggregation. Instrument before you need it; the outage is a bad time to add logging." },
    { id: "slo-sli", title: "SLOs and SLIs",
      keywords: ["slo", "sli", "reliability", "error budget"],
      body: "SLI = service level indicator (e.g., 99.5% of requests under 200ms). SLO = target for the SLI (e.g., maintain that over a quarter). Error budget = 1 - SLO; it's how much unreliability you can 'spend' shipping features. If you've blown your budget, stop shipping and stabilise. If you never use it, you're over-investing in reliability." },
    { id: "idempotency", title: "Idempotency",
      keywords: ["idempotent", "retry", "safe"],
      body: "An operation is idempotent if running it twice has the same effect as running it once. Crucial for retries — networks fail, messages dupe, users double-click. Design endpoints with idempotency keys (`POST /payments` with a `key` the client supplies; server dedupes). GET, PUT, DELETE are naturally idempotent; POST usually isn't without extra work." },
    { id: "graceful-degradation", title: "Graceful degradation",
      keywords: ["degrade", "fallback", "resilience"],
      body: "When a dependency fails, degrade gracefully instead of crashing. Search dead? Show recent popular items. Recommendations dead? Hide the widget. Payments dead? Queue the order. Circuit breakers (open when failure rate spikes, give up fast, auto-close when health returns) stop cascades." },
    { id: "tradeoffs", title: "Design is trade-offs",
      keywords: ["tradeoff", "design", "cost"],
      body: "Every architectural decision trades something for something else. Simplicity vs flexibility. Speed vs safety. Cost vs resilience. There are no right answers, only right trade-offs for your context (team size, user count, revenue, risk tolerance). Make trade-offs explicit in docs — future-you will ask why." },
  ],
};
