// Claude role — calls our Vercel /api/chat serverless function which proxies
// to Anthropic's Messages API. The key lives server-side only.
// Uses the same RAG pipeline as the local LLM: KB + closest template + live
// web search are stuffed into the system prompt for grounded answers.

import { buildContext, cleanCode } from "../modules/llm/rag.js";
import { bus }                     from "../core/bus.js";

export const claudeRole = {
  id: "claude",
  label: "Claude",

  async handle(text) {
    bus.emit("llm.generating", { prompt: text, via: "claude-api" });
    const system = await buildContext(text, { useWeb: true });

    try {
      const r = await fetch("/api/chat", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          system,
          messages: [{ role: "user", content: text }],
          max_tokens: 4096,
        }),
      });
      const data = await r.json().catch(() => ({}));
      bus.emit("llm.done", r.ok ? {} : { error: data.error || r.statusText });

      if (!r.ok) {
        return {
          text:
            `Claude API error (${r.status}): ${data.error?.message || data.error || r.statusText}. ` +
            `If this says "missing ANTHROPIC_API_KEY", set it in Vercel → Project → Settings → Environment Variables and redeploy.`,
        };
      }

      const code = cleanCode(data.text || "");
      const isBuild = /\b(code|build|make|create|generate|scaffold|write)\b/i.test(text);
      return {
        text: isBuild
          ? "Generated by Claude (with knowledge base + live web context) — loaded into the editor. Press Run ▶ to try it."
          : data.text || "",
        code: isBuild ? code : undefined,
        action: isBuild ? { kind: "load-editor", code } : undefined,
      };
    } catch (err) {
      bus.emit("llm.done", { error: err.message });
      return { text: `Claude request failed: ${err.message}` };
    }
  },
};
