// Local LLM role — runs a real generative model in the browser. Auto-loads a
// sensible default on first use (WebLLM + Qwen2.5-Coder if WebGPU is available,
// otherwise Transformers.js + a smaller Qwen-Coder). Always feeds the KB,
// composer templates, and live web search results as RAG context — no
// settings, no toggles, just works.

import { llm, pickDefaults }    from "../modules/llm/llm.js";
import { buildContext, cleanCode } from "../modules/llm/rag.js";
import { bus }                  from "../core/bus.js";

export const localLLMRole = {
  id: "local-llm",
  label: "AI Pro",

  async handle(text) {
    // Auto-load on first call. Progress is broadcast on the bus; the chat UI
    // listens and shows a status line so the user knows what's happening.
    if (!llm.isLoaded()) {
      const defaults = pickDefaults();
      bus.emit("llm.autoload.started", defaults);
      try {
        await llm.ensureLoaded(defaults);
      } catch (err) {
        return { text: `Couldn't load the local AI model: ${err.message}` };
      }
    }

    bus.emit("llm.generating", { prompt: text });
    const system = await buildContext(text, { useWeb: true });

    let streamed = "";
    try {
      const raw = await llm.generate({
        prompt: text,
        system,
        onToken: (_delta, full) => {
          streamed = full;
          bus.emit("llm.token", { full });
        },
      });
      const code = cleanCode(raw || streamed);
      bus.emit("llm.done", {});

      const isBuild = /\b(code|build|make|create|generate|scaffold|write)\b/i.test(text);
      return {
        text: isBuild
          ? "Generated by your local AI (with live web context) — loaded into the editor. Press Run ▶ to try it."
          : code,
        code,
        action: isBuild ? { kind: "load-editor", code } : undefined,
      };
    } catch (err) {
      bus.emit("llm.done", { error: err.message });
      return { text: `LLM error: ${err.message}` };
    }
  },
};
